Разметка
htmlacademy-adaptive/2320775-cat-energy-28 pull request #3
Opened 2023-04-01 13:57 UTC by AnnaVita1

2023-04-02 08:38 UTC, summertime-fms requested changes
Что сделано удачно: 

1. Блок features 
2. микс слайдера и блока example

Над чем подумать: 
1. Очень часто выделяешь мелкие элементы в отдельные бэм-блоки делая микс. На выходе у тебя получится огромное количество сущностей под каждую из которых будет свой файл потом. Не практично.
2. wrapper сейчас у каждого блока свой ( .block__wrapper) и будет ли удобно писать стили центровки в каждый блок отдельно или можно с этим что то сделать?..

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +<html class="page" lang="ru">
Написал в тг по этому поводу

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +    <div class="header__logo nav-logo">
выделила див с лого в отдельный переиспользуемый блок?..

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +        <span class="nav-logo__caption">Cat Energy</span>
Я думаю что надпись будет частью картинки, нельзя логотип как текст размечать, даже если это визуально как текст выглядит

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +    <div class="header__logo nav-logo">
В целом посоветую лучше от header стилизовать логотип а не от nav-logo (от nav-logo можно отказаться)

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +    <nav class="header-navigation">
header__nav + nav лучше сделать (на навигации уместен микс так как на некоторых сайтах навиагция есть и в хедере и в футере НО чаще всего эти навигации вообще друг на друга не похожи и смысла в таком случае в переиспользовании нет) Но тут я предлагаю тебе потренировать миксы

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +    <nav class="header-navigation">
И давай стремиться классы называть лаконичнее, потом замучаешься писать стили

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +      <button class="header-navigation__toggle" type="button">
есть еще классный атрибут `aria-pressed `на такие кнопки, но тут смысла мало так как кнопка только на мобилке отображается, скринридером вряд ли по ней пройдут

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +      <div class="offer__logo offer__logo--large">
Зачем модификатор? Будет не large? Тут будет ааптивная графика и она будет менять картинки на разных разрешениях так что в модификаторе тут нет смысла

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +        <img class="offer__image" src="#!" width="" height="" alt="Упаковка корма в стакане
Можно отказаться от класса так как мы ТОЧНО знаем что внутри всегда будет img. просто от обертки напишешь стили

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +      <div class="offer__button button-offer">
зачем выносить див с кнопкой в отдельный бэм-блок?.. у нас будут еще button-offer'ы на странице?

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +        <li class="features__item features-link">
Это же часть карточки. В карточке заголовок + текст + ссылка на каталог (а стрелка это не контентное изображение)

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +          <li class="description__item description__item--img-leaf">Функциональное питание
префикс img в модификаторе можно убрать

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +        <div class="example__description description-example">
Как и в случае с offer-button не понятно зачем второй класс

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +        <div class="example__results results-example">
Аналогично выше. Я бы не стал тут дробить на новый блок этот див - он выглядит так как будто он ТОЛЬКО в этом блоке и может сущестоввать, вряд ли кому то придет в голову его выдернуть

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +            <dt class="results-example__number">
Мы знаем что внутри dl ТОЧНО будут dl и dd а значит можно отказаться от классов и стилизовать от обертки

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +              </div>
это все один компонент а не множество отдельных. Тут можно от slider-example оттолкнуться и все контролы делать как slider-example__range slider-example__range slider-example__bar либо вынести этот полунок в блок range и от него уже тогда плодить элементы - range__scale range__bar и тд

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +        <p class="aside-invitation__description">ул. Большая
address

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +        <div class="footer__contacts nav-slogan">
зачем второй класс? лого футера будет сущестовать только внутри футера, у этого дива только один потомок - это не комплексный блок как например карточка товара или навигация в шапке, это просто див с картинкой, тут бэм не нужен

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +          <span class="nav-slogan__caption">Cat Energy</span>
А это будет изображением.

2023-04-02 08:38 UTC, summertime-fms commented on source/index.html
> +        <div class="footer__contacts nav-slogan">
upd
Понял твою логику посмотрев футер дальше. Вроде бы логично да, но подумай - 
для каждого бэмовского блока будет создавать свой отдельный файл стилей. Так например в cards.css будет лежать стили ТОЛЛКО для картчоек, в footer.css будут лежать стили только для футера. И вот будет у тебя файл nav-slogan.css и там будет лежать один селектор?..  Я бы тут лучше сделал footer__logo и засунул стили в будущем в footer.css и не парился бы

2023-04-02 09:16 UTC, AnnaVita1 commented on source/index.html
> +    <nav class="header-navigation">
По поводу nav Коля говорил что не надо лениться и сокращать))))

2023-04-02 09:39 UTC, AnnaVita1 commented on source/index.html
> +      <div class="offer__logo offer__logo--large">
А, понятно. Я думала что стаканы разные

2023-04-02 09:42 UTC, AnnaVita1 commented on source/index.html
> +<html class="page" lang="ru">
+ удалила

2023-04-02 09:43 UTC, AnnaVita1 commented on source/index.html
> +    <div class="header__logo nav-logo">
+ переделала

2023-04-02 09:53 UTC, AnnaVita1 commented on source/index.html
> +        <span class="nav-logo__caption">Cat Energy</span>
+ переделала, думала что текст

2023-04-02 09:54 UTC, AnnaVita1 commented on source/index.html
> +    <nav class="header-navigation">
+ переделала

2023-04-02 09:57 UTC, AnnaVita1 commented on source/index.html
> +      <div class="offer__logo offer__logo--large">
+исправила

2023-04-02 09:58 UTC, AnnaVita1 commented on source/index.html
> +        <img class="offer__image" src="#!" width="" height="" alt="Упаковка корма в стакане
+ исправила, логично

2023-04-02 10:00 UTC, AnnaVita1 commented on source/index.html
> +      <div class="offer__button button-offer">
+удалила. Думала что для того. что вдруг её захотят перемещать или добавлять. Ну как в теории написано)))

2023-04-02 10:10 UTC, AnnaVita1 commented on source/index.html
> +        <li class="features__item features-link">
+ удалила img и микс

2023-04-02 10:13 UTC, AnnaVita1 commented on source/index.html
> +          <li class="description__item description__item--img-leaf">Функциональное питание
+ удалила

2023-04-02 10:15 UTC, AnnaVita1 commented on source/index.html
> +        <div class="example__description description-example">
+ удалила

2023-04-02 10:17 UTC, AnnaVita1 commented on source/index.html
> +        <div class="example__results results-example">
+ удалила

2023-04-02 10:18 UTC, AnnaVita1 commented on source/index.html
> +            <dt class="results-example__number">
+ изменила

2023-04-02 10:22 UTC, AnnaVita1 commented on source/index.html
> +              </div>
slider-example__  оставила +

2023-04-02 10:27 UTC, AnnaVita1 commented on source/index.html
> +        <p class="aside-invitation__description">ул. Большая
+++ да, так лаконичнее

2023-04-02 10:29 UTC, AnnaVita1 commented on source/index.html
> +        <div class="footer__contacts nav-slogan">
Поменяю. простоя так подумать пока не могу, потоум что мы ещё не изучали препроцессоры)))))))))))))

2023-04-02 10:40 UTC, AnnaVita1 commented on source/index.html
> +          <span class="nav-slogan__caption">Cat Energy</span>
Сделала просто ссылку и изображение +

2023-04-03 14:18 UTC, summertime-fms requested changes

2023-04-03 14:18 UTC, summertime-fms commented on source/form.html
> +    <nav class="header-navigation navigation">
дак почему два новых блока на одном элементе?

2023-04-03 14:18 UTC, summertime-fms commented on source/form.html
> +        <form class="feedback-form" action="https://echo.htmlacademy.ru/" method="get">
feedback__form лучше

2023-04-03 14:18 UTC, summertime-fms commented on source/form.html
> +        <form class="feedback-form" action="https://echo.htmlacademy.ru/" method="get">
post

2023-04-03 14:18 UTC, summertime-fms commented on source/form.html
> +        <form class="feedback-form" action="https://echo.htmlacademy.ru/" method="get">
+ хорошая практика давать всем формам в рамках проекта общий класс form (по аналогии с button).чтобы упаковать в компоненты инпуты и чекбоксы, потом если понадобится форму добавить то достаточно будет просто классы правильные навесить, стили будут уже готовы. Соответственно форму нужно будет разметить по бэму

2023-04-03 14:18 UTC, summertime-fms commented on source/form.html
> +                  <span class="feedback-form__field-label">Имя:*</span>
используй sup чтобы поднять звездочку без написания доп стилей

2023-04-03 14:18 UTC, summertime-fms commented on source/form.html
> +          <fieldset class="feedback-form__box">
можно скрытую легенду сюда для доступности вставить

2023-04-03 14:18 UTC, summertime-fms commented on source/form.html
> +                  <input class="feedback-form__field-control input visually-hidden" type="radio" name="feedback-name" value="slim" checked>
А зачем тебе так много классов если инпут visually-hidden?

2023-04-03 14:18 UTC, summertime-fms commented on source/form.html
> +              </li>
где иконки?

2023-04-03 14:18 UTC, summertime-fms commented on source/index.html
> +          </li>
А почему в макете две картчоки а у тебя тут 4 элемента? Ссылки же это часть карточки

2023-04-03 14:18 UTC, summertime-fms commented on source/index.html
> +        <div class="footer__contacts social">
От дива можно отказаться в принципе, перенести классы с него на ul ниже т.к. лишний элемент как бы

2023-04-03 17:19 UTC, AnnaVita1 commented on source/form.html
> +    <nav class="header-navigation navigation">
++ Ошибка в подчёркивании, исправила на "header__navigation navigation"  - элемент хедера + блок

2023-04-03 17:36 UTC, AnnaVita1 commented on source/form.html
> +                  <span class="feedback-form__field-label">Имя:*</span>
+++ добавила

2023-04-03 17:38 UTC, AnnaVita1 commented on source/form.html
> +          <fieldset class="feedback-form__box">
+++добавила

2023-04-03 18:03 UTC, AnnaVita1 commented on source/form.html
> +        <form class="feedback-form" action="https://echo.htmlacademy.ru/" method="get">
+++ добавила post, и form переназвала.

2023-04-03 18:33 UTC, AnnaVita1 commented on source/form.html
> +                  <input class="feedback-form__field-control input visually-hidden" type="radio" name="feedback-name" value="slim" checked>
Да. в целом, да...

2023-04-03 18:41 UTC, AnnaVita1 commented on source/index.html
> +        <div class="footer__contacts social">
+++ удалила (так делали в барбершопе 🤣  я подсмотрела)

2023-04-03 20:11 UTC, AnnaVita1 commented on source/index.html
> +          </li>
Да надо было 2 ul, перепутала. Ну я переделала на дивах, так вроде меньше кода стало в два раза....

2023-04-03 20:12 UTC, AnnaVita1 commented on source/form.html
> +              </li>
Я думала они вставляются стили к инпуту...

2023-04-03 22:26 UTC, AnnaVita1 commented on source/form.html
> +              </li>
Пока что добавила модификатором в инпут, технически налепить в стилях бэкгрануд-имеджем. Пока по другому не знаю.

2023-04-04 09:35 UTC, merged